Someday my commits will become granular
Set gruvbox theme in system and vim
Update XDG user dirs
Add marks in vifm and aliases (with xdg user dirs)
Set bind for urls in dunst
Update xdg-open with env-wrapper/linkhandler scripts
Update sxhkd hotkeys
Remove underscore from script name
Use $() in scripts instead of ``
Disable banghist in zsh
Use brave as default browser
Update linkhandler for videos + remove ytstream
Fix picdir
[vim] Add options to ale linters
[vim] Add binds for visual selection
[vim] Add project drawer with netrw
[vim] Add sessions

diff --git a/.local/bin/linkhandler b/.local/bin/linkhandler
--- a/.local/bin/linkhandler
+++ b/.local/bin/linkhandler
@@ -1,16 +1,15 @@
 #!/bin/bash
 
 case "$1" in
-    *youtube.com/watch*|*youtube.com/playlist*|*youtu.be*)
-        notify-send "Opening" "$1"
-        setsid ytstream "$1" & ;;
-    *mkv|*webm|*mp4|*3gp|*avi)
-        setsid mpv -quiet "$1" >/dev/null 2>&1 & ;;
-    *png|*jpg|*jpe|*jpeg|*gif)
-        curl -sL "$1" > "/tmp/$(echo "$1" | sed "s/.*\///")" && sxiv -a "/tmp/$(echo "$1" | sed "s/.*\///")" ;;
-    *mp3|*flac|*opus|*mp3?source)
-        setsid tsp wget -P "$PODCASTS" "$1" >/dev/null 2>&1 & ;;
+    *youtube\.com/watch*|*youtube\.com/playlist*|*youtu\.be*|\
+    *youtube\.com%2Fwatch*|*youtube\.com%2Fplaylist*|\
+    *\.mkv|*\.webm|*\.mp4|*\.3gp|*\.avi)
+        notify-send "Opening in MPV" "$1"
+        ERROR=$( (youtube-dl -F "$1" 3>&2 2>&1 1>&3) 2>/dev/null)
+        [[ "$?" -ne "0" ]] && notify-send "Youtube-dl error" "$ERROR" && exit 1
+        setsid mpv \
+            --ytdl-format="bestvideo[height<=1080]+bestaudio/best[height<=1080]"\
+            -quiet "$1" >/dev/null 2>&1 & ;;
     *)
-        browser=$(sed -n '/BROWSER/s/.\+"\(.\+\)"/\1/p' ~/.profile)
-        setsid "$browser" "$1" >/dev/null 2>&1 & ;;
+        setsid "$BROWSER" "$1" >/dev/null 2>&1 & ;;
 esac
