Add tsp for yt-dl, change zsh highlight, etc
Add tsp for youtube-dl: ytloader and newsboat config
Change zsh syntax highlight
Change sshrc bashrc prompt
Set tsp slots in profile
Small scripts updates
Add statusbar toggling in zathura
Add russian letters for quetbrowser prompt
Vim: new markdown syntax, shellcheck linter, hidden files search with rg
Git: add gm = git merge
Add cycle binding in mpv
Increase low resolution format in ytloader
Set theme for sshrc bashrc

diff --git a/.local/bin/ytloader b/.local/bin/ytloader
--- a/.local/bin/ytloader
+++ b/.local/bin/ytloader
@@ -7,6 +7,13 @@ outaudio="$(xdg-user-dir MUSIC)"
 filename='%(title)s.%(ext)s'
 format="m"
 
+msg_download="YTLoader: Downloading"
+msg_no_url="YTLoader: No URL given"
+msg_fail="YTLoader: Download failed"
+msg_invalid_format="YTLoader: Invalid format"
+msg_loaded="YTLoader: Loaded"
+msg_invalid_flag="YTLoader: Invalid option"
+
 print_help() {
     echo "Usage: ytloader [options] link"
     echo "Description: downloads music and video from youtube"
@@ -14,7 +21,7 @@ print_help() {
     echo "    -f - format."
     echo "         'a' - audio"
     echo "         'l' - low quality video (up to 240p)"
-    echo "         'm' - medium quality video (up to 1080p)"
+    echo "         'm' - medium quality video (up to 1080p) [default]"
     echo "         'h' - high quality video (best quality available)"
     echo "    -s - download video with subtitles (if available)"
     echo "    -d - subdirectory for file. Appends to default music/video path"
@@ -28,13 +35,14 @@ while getopts "f:d:suh" opt; do
         s) with_subs="--all-subs" ;;
         u) filename='%(uploader)s - %(title)s.%(ext)s' ;;
         h) print_help ; exit 0 ;;
+        *) exit 1 ;;
     esac
 done
 
-shift $(($OPTIND-1))
+shift $((OPTIND-1))
 link=$1
 
-[ -z "$link" ] && echo -e "Error: No URL to download given\n" && print_help && exit
+[ -z "$link" ] && echo "$msg_no_url" && notify-send "$msg_no_url" && print_help && exit
 
 if [ -z "$subdir" ]; then
     outaudio="${outaudio}/downloads"
@@ -46,14 +54,19 @@ fi
 [ ! -d "$outaudio" ] && mkdir -p "$outaudio"
 [ ! -d "$outvideo" ] && mkdir -p "$outvideo"
 
-notify-send "Downloading" "$link"
+notify-send "$msg_download" "$link"
+
+check_error() {
+    error_code="$?"
+    [ $error_code -ne 0 ] && notify-send "$msg_fail" "Error code ($error_code)\n$link" && exit $error_code
+}
 
 case $format in
     'a') youtube-dl --add-metadata -icxf "bestaudio/best" -o "$outaudio/$filename" "$link" ;;
-    'l') youtube-dl --add-metadata $with_subs -icf "best[height<=240]" -o "$outvideo/$filename" "$link" ;;
+    'l') youtube-dl --add-metadata $with_subs -icf "best[height<=360]" -o "$outvideo/$filename" "$link" ;;
     'm') youtube-dl --add-metadata $with_subs -icf "bestvideo[height<=1080]+bestaudio/best" -o "$outvideo/$filename" "$link" ;;
     'h') youtube-dl --add-metadata $with_subs -icf "bestvideo+bestaudio/best" -o "$outvideo/$filename" "$link" ;;
-    *) echo "Incorrect format"
-esac
+    *) notify-send "$msg_invalid_format" "Format ($format)\n$link" ; exit 1 ;;
+esac ; check_error
 
-notify-send "Loaded" "$link"
+notify-send "$msg_loaded" "$link"
